/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainChatRouteRouteImport } from './routes/_main/chat/route'
import { Route as MainChatFriendsRouteImport } from './routes/_main/chat/friends'
import { Route as MainChatChatindexRouteRouteImport } from './routes/_main/chat/_chatindex/route'
import { Route as MainChatChatindexIndexRouteImport } from './routes/_main/chat/_chatindex/index'
import { Route as MainChatChatindexUsernameRouteImport } from './routes/_main/chat/_chatindex/$username'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainChatRouteRoute = MainChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainChatFriendsRoute = MainChatFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => MainChatRouteRoute,
} as any)
const MainChatChatindexRouteRoute = MainChatChatindexRouteRouteImport.update({
  id: '/_chatindex',
  getParentRoute: () => MainChatRouteRoute,
} as any)
const MainChatChatindexIndexRoute = MainChatChatindexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainChatChatindexRouteRoute,
} as any)
const MainChatChatindexUsernameRoute =
  MainChatChatindexUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => MainChatChatindexRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat': typeof MainChatChatindexRouteRouteWithChildren
  '/chat/friends': typeof MainChatFriendsRoute
  '/chat/$username': typeof MainChatChatindexUsernameRoute
  '/chat/': typeof MainChatChatindexIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat': typeof MainChatChatindexIndexRoute
  '/': typeof MainIndexRoute
  '/chat/friends': typeof MainChatFriendsRoute
  '/chat/$username': typeof MainChatChatindexUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_main/chat': typeof MainChatRouteRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/chat/_chatindex': typeof MainChatChatindexRouteRouteWithChildren
  '/_main/chat/friends': typeof MainChatFriendsRoute
  '/_main/chat/_chatindex/$username': typeof MainChatChatindexUsernameRoute
  '/_main/chat/_chatindex/': typeof MainChatChatindexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/chat'
    | '/chat/friends'
    | '/chat/$username'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/chat'
    | '/'
    | '/chat/friends'
    | '/chat/$username'
  id:
    | '__root__'
    | '/_main'
    | '/signin'
    | '/signup'
    | '/_main/chat'
    | '/_main/'
    | '/_main/chat/_chatindex'
    | '/_main/chat/friends'
    | '/_main/chat/_chatindex/$username'
    | '/_main/chat/_chatindex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/chat': {
      id: '/_main/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof MainChatRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/chat/friends': {
      id: '/_main/chat/friends'
      path: '/friends'
      fullPath: '/chat/friends'
      preLoaderRoute: typeof MainChatFriendsRouteImport
      parentRoute: typeof MainChatRouteRoute
    }
    '/_main/chat/_chatindex': {
      id: '/_main/chat/_chatindex'
      path: ''
      fullPath: '/chat'
      preLoaderRoute: typeof MainChatChatindexRouteRouteImport
      parentRoute: typeof MainChatRouteRoute
    }
    '/_main/chat/_chatindex/': {
      id: '/_main/chat/_chatindex/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof MainChatChatindexIndexRouteImport
      parentRoute: typeof MainChatChatindexRouteRoute
    }
    '/_main/chat/_chatindex/$username': {
      id: '/_main/chat/_chatindex/$username'
      path: '/$username'
      fullPath: '/chat/$username'
      preLoaderRoute: typeof MainChatChatindexUsernameRouteImport
      parentRoute: typeof MainChatChatindexRouteRoute
    }
  }
}

interface MainChatChatindexRouteRouteChildren {
  MainChatChatindexUsernameRoute: typeof MainChatChatindexUsernameRoute
  MainChatChatindexIndexRoute: typeof MainChatChatindexIndexRoute
}

const MainChatChatindexRouteRouteChildren: MainChatChatindexRouteRouteChildren =
  {
    MainChatChatindexUsernameRoute: MainChatChatindexUsernameRoute,
    MainChatChatindexIndexRoute: MainChatChatindexIndexRoute,
  }

const MainChatChatindexRouteRouteWithChildren =
  MainChatChatindexRouteRoute._addFileChildren(
    MainChatChatindexRouteRouteChildren,
  )

interface MainChatRouteRouteChildren {
  MainChatChatindexRouteRoute: typeof MainChatChatindexRouteRouteWithChildren
  MainChatFriendsRoute: typeof MainChatFriendsRoute
}

const MainChatRouteRouteChildren: MainChatRouteRouteChildren = {
  MainChatChatindexRouteRoute: MainChatChatindexRouteRouteWithChildren,
  MainChatFriendsRoute: MainChatFriendsRoute,
}

const MainChatRouteRouteWithChildren = MainChatRouteRoute._addFileChildren(
  MainChatRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainChatRouteRoute: typeof MainChatRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainChatRouteRoute: MainChatRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
