/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainChatRouteRouteImport } from './routes/_main/chat/route'
import { Route as MainChatIndexRouteImport } from './routes/_main/chat/index'
import { Route as MainChatUsernameRouteImport } from './routes/_main/chat/$username'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/_main/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainChatRouteRoute = MainChatRouteRouteImport.update({
  id: '/_main/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MainChatIndexRoute = MainChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainChatRouteRoute,
} as any)
const MainChatUsernameRoute = MainChatUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat': typeof MainChatRouteRouteWithChildren
  '/': typeof MainIndexRoute
  '/chat/$username': typeof MainChatUsernameRoute
  '/chat/': typeof MainChatIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/': typeof MainIndexRoute
  '/chat/$username': typeof MainChatUsernameRoute
  '/chat': typeof MainChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_main/chat': typeof MainChatRouteRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/chat/$username': typeof MainChatUsernameRoute
  '/_main/chat/': typeof MainChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signup'
    | '/chat'
    | '/'
    | '/chat/$username'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/signup' | '/' | '/chat/$username' | '/chat'
  id:
    | '__root__'
    | '/signin'
    | '/signup'
    | '/_main/chat'
    | '/_main/'
    | '/_main/chat/$username'
    | '/_main/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  MainChatRouteRoute: typeof MainChatRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/chat': {
      id: '/_main/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof MainChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/chat/': {
      id: '/_main/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof MainChatIndexRouteImport
      parentRoute: typeof MainChatRouteRoute
    }
    '/_main/chat/$username': {
      id: '/_main/chat/$username'
      path: '/$username'
      fullPath: '/chat/$username'
      preLoaderRoute: typeof MainChatUsernameRouteImport
      parentRoute: typeof MainChatRouteRoute
    }
  }
}

interface MainChatRouteRouteChildren {
  MainChatUsernameRoute: typeof MainChatUsernameRoute
  MainChatIndexRoute: typeof MainChatIndexRoute
}

const MainChatRouteRouteChildren: MainChatRouteRouteChildren = {
  MainChatUsernameRoute: MainChatUsernameRoute,
  MainChatIndexRoute: MainChatIndexRoute,
}

const MainChatRouteRouteWithChildren = MainChatRouteRoute._addFileChildren(
  MainChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  MainChatRouteRoute: MainChatRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
